fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.6.0"
    inifile:
      repo: "puppetlabs/inifile"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.5"
    java_ks:
      repo: "puppetlabs/java_ks"
      ref: "1.4.1"
  symlinks:
    nifi: "#{source_dir}"
