HOSTS:
  nifi-as01a:
    roles:
      - agent
      - centos
    platform: el-7-x86_64
    hypervisor: docker
    image:  c7-nifi-puppet:latest
    docker_container_name: nifi-as01a
    docker_preserve_image: false
CONFIG:
  log_level: verbose
  type: foss